remote_theme: BDHU/minimalist
highlighter: rogue

title: Table of Contents


descriptionTitle: Description
finalTitle: Outcome
leadupTitle: The leadup
competitionTitle: The competition

projectBy: Project by Hayden Hirsch
projectSchool: Gibson Ek High School
livereload: True